services:
  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: postgres-sae
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: masterbook
    ports:
      - "5432:5432"
    volumes:
      - db_data_masterbook:/var/lib/postgresql/data
    networks:
      - db_network

  elasticsearch:
    image: bitnami/elasticsearch:8.17.1
    container_name: my-es-sae
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms4096m -Xmx4096m # Pour pas que ES prennent TOUTES la ram
    volumes:
      - elasticsearch-data-persistence:/bitnami/elasticsearch/data
    networks:
      - es  

  server:
    restart : "on-failure"
    container_name: fastapi_server
    depends_on:
      - postgres
      - elasticsearch
    build:
      context: ./fastapi
    ports:
      - 8000:8000
    networks:
      - es 
      - db_network
      - ollama

networks:
  es:
  db_network:
  ollama:

volumes:
  db_data_masterbook:
  elasticsearch-data-persistence:
  ollama: