version: '3.9'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-local
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: masterbook
    ports:
      - "5432:5432"
    volumes:
      - db_data_masterbook:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data_masterbook:
